language: cpp

compiler:
  - gcc
  - clang

before_install:
  - wget http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.bz2
  - tar --bzip2 -xf boost_1_54_0.tar.bz2
  - cd boost_1_54_0
  - sudo ./bootstrap.sh
  - sudo ./b2 install
  - cd ..
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: cmake . && make
