language: cpp

compiler:
  - gcc
  - clang

before_install:
  - wget http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.bz2
  - tar --bzip2 -xf boost_1_54_0.tar.bz2
  - cd boost_1_54_0
  - sudo ./bootstrap.sh
  - sudo ./b2 install
  - cd ..

script: cmake . && make
